### PR TITLE
Data link PollutantList view

### PR DESCRIPTION
**Pull request by CoreyPatrickPDX**
This is the first PR for linking the data from the API to the views. I've decided I will create a pull request as I tie the data to each view so it isn't a lot of code in each.

In this PR:
- A new file for API services was created for a more general way to call the API
- A getAllPollutants method was created to get all pollutants that are tracked by the API from the Get Parameters call (https://docs.openaq.org/reference/parameters_get_v2_parameters_get)
- Updated the ParametersList view so the values from getAllPollutants are used to fill out the options for pollutants
    - There are multiples for some pollutants so the value of the options are based on the name and preferred measurement of the pollutants to make life easier in the future.
- A few minor changes, commented out some console.log statements so they don't flood the console, some error fixes

Need to do:
- List details of each pollutant
- Link the data to the other views as needed
- Implement the search feature

Issues with views:
- I'm not sure if it's just for me, but the Main and Historical page are cut off by a little bit at the top. In 'Historical" I'm unable to click on anything in the navbar because of this.
- 
image
image

### CODE REVIEW

**Review by gleason9113 — COMMENTED** [review]
This all looks good to me.  Two questions:

1.  Is there a reason to prefer getting a list of pollutants via an API call each time vs simply having the list in the code, which I *think* would be more efficient?
2.  Why not keep all the API calls in the api.js file - I think that that would be clearer organization, wouldn't it?

**Comment by CoreyPatrickPDX** [comment]
1. You are completely right, I'll change this to a service that is called once at the beginning of the view.
2. I didn't want to change what you had already written in the api.js. I find it easier to set up a more generic call that can be added on to filter results like I did for getting all of the pollutants and I wanted to bring it up as a discussion.

**Comment by CoreyPatrickPDX** [comment]
Okay, I moved the generic axios API call setup and the call to get the pollutant data to the api.js file. I'm not sure how to setup a way to get the pollutant data only once but I can look at it in my next section of work.

**Comment by gleason9113** [comment]
My thought was that it's probably a faster operation to simply declare an array containing the pollutant names rather than make an API call to get the names. 

It's fine either way, was just curious.  Approved.

**Pull request merged**
