### PR TITLE
Api3

### PR DESCRIPTION
**Pull request by gleason9113**
Changes:
-Added API calls and form for DetailedView.
-Added API calls and form for HistoricalView

I have API calls added here for search by country, search by city, and search for city during time period.  I've added basic unstyled form elements to the pages - these need to be prettied up.   Not sure what the plan is with the historical data - it's by city during date range, there's a lot for even a small query, from what I've seen.

### CODE REVIEW

**Review by A-Basirat — COMMENTED** [review]
The API part is working well, but the historical view is not showing any information. I have been making changes to the views and adding more elements to them. To prevent any conflicts with your code, we should work on separate files. So, please move the elements related to the search box to a new component called "Search.js" and revert the views to how they were before this recent change. I will push my changes soon, and then Corey can complete the search functionality and integrate it into the views.

**Comment by gleason9113** [comment]
Restored the HistoricalView to the version from the main branch.  What issue were you seeing with the console output?

**Comment by A-Basirat** [comment]
> Restored the HistoricalView to the version from the main branch. What issue were you seeing with the console output?

**Review by A-Basirat — COMMENTED** [review]
I got no error or issue on the console!

Thanks for restoring the views.

**Pull request closed without merging**
